#jpa
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: hash_map    #session\u4F1A\u8BDD\u7BA1\u7406
  profiles:
    active: dev
  thymeleaf:                #thymeleaf
    mode: HTML
  resources:                #静态资源访问
    static-locations: classpath:/static/
  devtools:
    restart:
      exclude: templates/**,static/**

#\u5173\u95EDhttp\u9A8C\u8BC1
security:
  basic:
    enabled: false
logging:
  level: debug

#qiniu
qiniu:
  AccessKey: 5_plndB1D335QPzapLgBEY5JI8OBTIiB15_9GEZ_
  SecretKey: VmPtaT4PfpkaTPzjNga7cjm0jSsAK2yd1O5V-5S7
  Bucket: zb-qixiu
  cdn:
    prefix: p8106shz2.bkt.clouddn.com